// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Subsystem.

package frc.robot.subsystems;

import com.revrobotics.AbsoluteEncoder;
import com.revrobotics.CANSparkMax;
import com.revrobotics.CANSparkMaxLowLevel.MotorType;
import com.revrobotics.SparkMaxAbsoluteEncoder.Type;

import edu.wpi.first.math.controller.PIDController;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.SubsystemBase;

import frc.robot.Constants;

public class Arm extends SubsystemBase {
    private CANSparkMax arm;
    private AbsoluteEncoder encoder;
    private edu.wpi.first.math.controller.PIDController pidController;

    private final double kP = 0.01;
    private final double kI = 0.0001;
    private final double kD = 0.0;

    public Arm() {
        arm = new CANSparkMax(15, MotorType.kBrushless);
        
        // Restore factory defaults before configuring the arm
        arm.restoreFactoryDefaults();
        
        encoder = arm.getAbsoluteEncoder(Type.kDutyCycle);
        pidController = new PIDController(kP, kI, kD);

        // Set position conversion factor for the encoder
//        encoder.setPositionConversionFactor(1);

        // Invert the encoder if necessary
//        encoder.setInverted(false);
        
        // Save the arm configuration
        arm.burnFlash();
    }

    public void setPosition(double targetPosition) {
        pidController.setSetpoint(targetPosition);
    }

    public double getPosition() {
        return encoder.getPosition();
    }

    @Override
    public void periodic() {
        // This method will be called once per scheduler run
        double output = pidController.calculate(getPosition());
        arm.set(output);
        SmartDashboard.putNumber("ArmPosition", getPosition());
    }

    @Override
    public void simulationPeriodic() {
        // This method will be called once per scheduler run when in simulation
    }
}