// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Command.

//package frc.robot.commands;
//import edu.wpi.first.wpilibj2.command.CommandGroupBase;
//import edu.wpi.first.wpilibj2.command.ParallelRaceGroup;
//import edu.wpi.first.wpilibj2.command.SequentialCommandGroup;
//import frc.robot.subsystems.Conveyor;
//import frc.robot.subsystems.DriveTrain;
//import frc.robot.subsystems.Intake;
//import frc.robot.subsystems.Shooter;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 *
 */
//public class AutonomousTestForwardBack extends SequentialCommandGroup {

    //public AutonomousTestForwardBack(Intake theIntake, Shooter shooter,Conveyor theConveyor, DriveTrain theDriveTrain){

        //TODO create a startShooterLow command (so it will keep running, all during auton) and 
        //TODO create a StartIntake command

    //Reset the Gyro

        //addCommands(new GyroReset(theDriveTrain));
        //addCommands( new DriveTrainMoveStraight(theDriveTrain, 100 /*Distance*/, 3 /*maxSpeed ft/sec*/, 10 /*inch to get to maxSpeed*/, 0 /*Angle to drive straight on*/ ));
        //addCommands( new DriveTrainMoveStraight(theDriveTrain, -100 /*Distance*/, 5 /*maxSpeed ft/sec*/, 10 /*inch to get to maxSpeed*/, 0 /*Angle to drive straight on*/));  
//        addCommands( new DriveTrainMoveStraightFaster(theDriveTrain, 100 /*Distance*/, 3 /*maxSpeed ft/sec*/, 10 /*inch to get to maxSpeed*/, 0 /*Angle to drive straight on*/, 1 /*Inches Tolerance */ ));
//        addCommands( new DriveTrainMoveStraightFaster(theDriveTrain, -100 /*Distance*/, 5 /*maxSpeed ft/sec*/, 10 /*inch to get to maxSpeed*/, 0 /*Angle to drive straight on*/, 1 /*Inches Tolerance */));  
    //}

//}
