// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Command.

//package frc.robot.commands;
//import edu.wpi.first.wpilibj2.command.CommandGroupBase;
//import edu.wpi.first.wpilibj2.command.SequentialCommandGroup;
//import frc.robot.subsystems.Conveyor;
//import frc.robot.subsystems.DriveTrain;
//import frc.robot.subsystems.Intake;
//import frc.robot.subsystems.Shooter;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 *
 */
//public class AutonomousShootandBackup extends SequentialCommandGroup {
        //public AutonomousShootandBackup(Intake theIntake, Shooter shooter,Conveyor theConveyor, DriveTrain theDriveTrain){
//did work runtime error        addCommands(new ShooterMoveLow(RobotContainer.getInstance().m_shooter));
//addCommands(new ShooterMoveLow(RobotContainer.getInstance().m_shooter));
//addCommands(new ShooterMoveLow(shooter).withTimeout(2));                                     
//CommandGroupBase spinAndShootAndintake = SequentialCommandGroup.parallel(
                                              //new ShooterMoveLow(shooter),
                                              //new IntakeMove(theIntake),
                                              //new ConveyorMove(theConveyor)).withTimeout(5);

        //addCommands(spinAndShootAndintake);
      // addCommands(new ShooterMoveLow(shooter));
       // addCommands(new ConveyorMove(theConveyor));
      // addCommands(new IntakeDeployTimed(theIntake, theConveyor));
       //addCommands(new ShooterMoveLowTimed(shooter));
       //addCommands(new DriveTrainMovedTimed(theDriveTrain));
       
    //}

//}
